### ISSUE TITLE
Please remove this repository or make it private

### ISSUE THREAD

**Issue by ayanc** [lizoyu/cse559a-2017fall#1]
Folks,

Publicly posting your solutions to the problem sets is helping other people (who are taking the course this semester) cheat. While it is of course primarily the fault of the people who are cheating, I would request that you remove this repository or make it private.

Professor Chakrabarti

**Comment by lizoyu** [comment]
@ayanc Sorry, prof. Solutions are now put in encrypted zip files.

**Comment by ayanc** [comment]
Thanks. I appreciate it.

Unfortunately, the code is still there and available in the repository history / older commits. It would be great if you could just create a fresh repo with the just the encrypted zip files (just copy of the zip files to a new directory, delete this repo and create it again, and then upload/push the zip files).
